import type { Cycle } from '@/shared/types'

export const financeCycles: Cycle[] = [
  {
    id: 'budgets',
    title: 'Budgets',
    area: 'finance',
    effort: 'heavy',
    must: true,
    triggerLabel: 'Starts 20th of month',
    status: 'active',
    items: [
      {
        id: 'b1',
        label: 'Screen for payment requests',
        status: 'todo',
        effort: 'medium',
        notes: '',
        subItems: [
          { id: 'b1a', label: 'Emails', status: 'todo', effort: 'quick' },
          { id: 'b1b', label: 'All chats (Lark, WeChat, Telegram)', status: 'todo', effort: 'quick' },
          { id: 'b1c', label: 'ADGM budgets', status: 'todo', effort: 'quick' },
        ],
      },
      {
        id: 'b2',
        label: 'Complete budget sheets',
        status: 'todo',
        effort: 'heavy',
        notes: '',
      },
      {
        id: 'b3',
        label: 'Send budget emails',
        status: 'todo',
        effort: 'quick',
        notes: '',
      },
      {
        id: 'b4',
        label: 'Allocate funds + mark records',
        status: 'todo',
        effort: 'medium',
        notes: '',
        subItems: [
          { id: 'b4a', label: '(sub-step TBC)', status: 'todo', effort: 'quick' },
          { id: 'b4b', label: '(sub-step TBC)', status: 'todo', effort: 'quick' },
        ],
      },
    ],
  },
  {
    id: 'payroll',
    title: 'Payroll',
    area: 'finance',
    effort: 'heavy',
    must: true,
    triggerLabel: 'Phase 1: 20th · Phase 2: Last 5 days · Phase 3: 1st work day',
    status: 'upcoming',
    phases: [
      {
        id: 'payroll-planning',
        title: 'Phase 1 — Planning',
        triggerLabel: 'Starts 20th of month',
        effort: 'heavy',
        must: true,
        status: 'upcoming',
        items: [
          { id: 'p1a', label: 'Check notes', status: 'todo', effort: 'quick' },
          { id: 'p1b', label: 'Generate new month payroll', status: 'todo', effort: 'medium' },
          { id: 'p1c', label: 'Ask for MOD salaries + check with CFO', status: 'todo', effort: 'quick', waitingOn: true },
          { id: 'p1d', label: 'Confirm budget', status: 'todo', effort: 'quick' },
          { id: 'p1e', label: 'Ask team leaders to fill in HR headcount cost sheets', status: 'todo', effort: 'quick', waitingOn: true },
        ],
      },
      {
        id: 'payroll-settlement',
        title: 'Phase 2 — Settlement',
        triggerLabel: 'Last 5 days of month',
        effort: 'heavy',
        must: true,
        status: 'upcoming',
        items: [
          { id: 'p2a', label: 'Send email to BCOM', status: 'todo', effort: 'quick' },
          { id: 'p2b', label: 'Fiat: EV Tech BCOM, Apexco BCOM, DT HSBC, OA Airwallex, ADFL Zand', status: 'todo', effort: 'heavy' },
          { id: 'p2c', label: 'Fiat: GAHK Shacom', status: 'todo', effort: 'medium' },
          { id: 'p2d', label: 'Crypto: plan crypto settlement', status: 'todo', effort: 'medium' },
          { id: 'p2e', label: 'Arrange funds from sub-account to main account + records', status: 'todo', effort: 'medium' },
          { id: 'p2f', label: 'Crypto + MOD salaries settlement', status: 'todo', effort: 'medium' },
        ],
      },
      {
        id: 'payroll-2nd-round',
        title: 'Phase 3 — 2nd Round Settlement',
        triggerLabel: '1st work day of next month',
        effort: 'heavy',
        must: true,
        status: 'upcoming',
        items: [
          { id: 'p3a', label: 'Settle driver salary + PT salary', status: 'todo', effort: 'medium' },
          { id: 'p4', label: 'HR headcount cost', status: 'todo', effort: 'quick' },
        ],
      },
    ],
  },
  {
    id: 'bank-statements-weekly',
    title: 'Bank Statements — Weekly',
    area: 'finance',
    effort: 'quick',
    must: true,
    triggerLabel: 'Every Monday',
    status: 'upcoming',
    items: [
      {
        id: 'bsw1',
        label: 'Bank CSV upload',
        status: 'todo',
        effort: 'quick',
        subItems: [
          { id: 'bsw1a', label: 'BCOM: EV Tech, Duom', status: 'todo', effort: 'quick' },
          { id: 'bsw1b', label: 'Fusion: EV Tech, GAHK', status: 'todo', effort: 'quick', url: 'internal-sheet' },
        ],
      },
    ],
  },
  {
    id: 'bank-statements-monthly',
    title: 'Bank Statements — Monthly',
    area: 'finance',
    effort: 'heavy',
    must: true,
    triggerLabel: 'Every 2nd of month',
    status: 'upcoming',
    items: [
      { id: 'bsm1', label: 'Bank CSV upload', status: 'todo', effort: 'quick', url: 'internal-sheet' },
      { id: 'bsm2', label: 'Bank statements — full monthly', status: 'todo', effort: 'heavy' },
      { id: 'bsm3', label: 'Credit cards', status: 'todo', effort: 'medium' },
    ],
  },
  {
    id: 'bank-statements-midmonth',
    title: 'Bank Statements — Mid-Month',
    area: 'finance',
    effort: 'medium',
    must: true,
    triggerLabel: 'Every 17th of month',
    status: 'upcoming',
    items: [
      { id: 'bsmm1', label: 'BCOMs: EV Tech, Apexco, ML Tech, Everest, Duom', status: 'todo', effort: 'medium', url: 'internal-sheet' },
      { id: 'bsmm2', label: 'HSBC: Unik', status: 'todo', effort: 'quick', url: 'internal-sheet' },
    ],
  },
  {
    id: 'reap-credit-card',
    title: 'Reap Credit Card',
    area: 'finance',
    effort: 'quick',
    must: true,
    triggerLabel: 'Every 17th of month',
    status: 'upcoming',
    items: [
      { id: 'rcc1', label: 'GAHK', status: 'todo', effort: 'quick' },
      { id: 'rcc2', label: 'EV Tech', status: 'todo', effort: 'quick' },
    ],
  },
]
