import type { Cycle } from '@/shared/types'

export const financeCycles: Cycle[] = [
  {
    id: 'ai-accounting-system',
    title: 'AI Accounting System',
    area: 'finance',
    subArea: 'AI',
    effort: 'heavy',
    must: false,
    triggerLabel: '',
    status: 'active',
    items: [
      { id: 'aas1', label: 'Teach Claude to read bank transactions', status: 'todo', effort: 'medium' },
      { id: 'aas2', label: "Check Jenny's progress on GL mapping", status: 'todo', effort: 'quick', waitingOn: true },
      { id: 'aas3', label: 'Discuss description renaming with AI', status: 'todo', effort: 'quick' },
      { id: 'aas4', label: "Save Jenny's 2 script folder", status: 'todo', effort: 'quick' },
    ],
  },
  {
    id: 'bcom-admin-duties',
    title: 'BCOM Admin Duties',
    area: 'finance',
    subArea: 'Administrative',
    effort: 'quick',
    must: false,
    triggerLabel: '',
    status: 'active',
    items: [
      { id: 'bad1', label: 'AD tech token renew form', status: 'todo', effort: 'quick' },
      { id: 'bad2', label: 'AD tech pw renew form', status: 'todo', effort: 'quick' },
      { id: 'bad3', label: 'EV tech signature renew form', status: 'todo', effort: 'quick' },
      { id: 'bad4', label: 'Apexco token renew form', status: 'todo', effort: 'quick' },
    ],
  },
  {
    id: 'adfl-zand',
    title: 'ADFL Zand',
    area: 'finance',
    subArea: 'Payments',
    effort: 'medium',
    must: false,
    triggerLabel: '',
    status: 'active',
    items: [
      { id: 'az1', label: "Check Joyce Valle's email", status: 'todo', effort: 'quick' },
      { id: 'az2', label: 'TBC', status: 'todo', effort: 'medium' },
    ],
  },
  {
    id: 'budgets',
    title: 'Budgets',
    area: 'finance',
    subArea: 'Budgets',
    effort: 'heavy',
    must: true,
    triggerLabel: 'Starts 20th of month',
    status: 'active',
    items: [
      {
        id: 'b1',
        label: 'Screen for payment requests',
        status: 'todo',
        effort: 'medium',
        notes: '',
        subItems: [
          { id: 'b1a', label: 'Emails', status: 'todo', effort: 'quick' },
          { id: 'b1b', label: 'All chats (Lark, WeChat, Telegram)', status: 'todo', effort: 'quick' },
          { id: 'b1c', label: 'ADGM budgets', status: 'todo', effort: 'quick' },
        ],
      },
      { id: 'b2', label: 'Complete budget sheets', status: 'todo', effort: 'heavy', notes: '' },
      { id: 'b3', label: 'Send budget emails', status: 'todo', effort: 'quick', notes: '' },
      {
        id: 'b4',
        label: 'Allocate funds + mark records',
        status: 'todo',
        effort: 'medium',
        notes: '',
        subItems: [
          { id: 'b4a', label: '(sub-step TBC)', status: 'todo', effort: 'quick' },
          { id: 'b4b', label: '(sub-step TBC)', status: 'todo', effort: 'quick' },
        ],
      },
    ],
  },
  {
    id: 'bank-statements-weekly',
    title: 'Bank Statements — Weekly',
    area: 'finance',
    subArea: 'Records',
    effort: 'quick',
    must: true,
    triggerLabel: 'Every Monday',
    status: 'upcoming',
    items: [
      {
        id: 'bsw1',
        label: 'Bank CSV upload',
        status: 'todo',
        effort: 'quick',
        subItems: [
          { id: 'bsw1a', label: 'BCOM: EV Tech, Duom', status: 'todo', effort: 'quick' },
          { id: 'bsw1b', label: 'Fusion: EV Tech, GAHK', status: 'todo', effort: 'quick', url: 'internal-sheet' },
        ],
      },
    ],
  },
  {
    id: 'bank-statements-monthly',
    title: 'Bank Statements — Monthly',
    area: 'finance',
    subArea: 'Records',
    effort: 'heavy',
    must: true,
    triggerLabel: 'Every 2nd of month',
    status: 'upcoming',
    items: [
      { id: 'bsm1', label: 'Bank CSV upload', status: 'todo', effort: 'quick', url: 'internal-sheet' },
      { id: 'bsm2', label: 'Bank statements — full monthly', status: 'todo', effort: 'heavy' },
      { id: 'bsm3', label: 'Credit cards', status: 'todo', effort: 'medium' },
    ],
  },
  {
    id: 'bank-statements-midmonth',
    title: 'Bank Statements — Mid-Month',
    area: 'finance',
    subArea: 'Records',
    effort: 'medium',
    must: true,
    triggerLabel: 'Every 17th of month',
    status: 'upcoming',
    items: [
      { id: 'bsmm1', label: 'BCOMs: EV Tech, Apexco, ML Tech, Everest, Duom', status: 'todo', effort: 'medium', url: 'internal-sheet' },
      { id: 'bsmm2', label: 'HSBC: Unik', status: 'todo', effort: 'quick', url: 'internal-sheet' },
    ],
  },
  {
    id: 'reap-credit-card',
    title: 'Reap Credit Card',
    area: 'finance',
    subArea: 'Payments',
    effort: 'quick',
    must: true,
    triggerLabel: 'Every 17th of month',
    status: 'upcoming',
    items: [
      { id: 'rcc1', label: 'GAHK', status: 'todo', effort: 'quick' },
      { id: 'rcc2', label: 'EV Tech', status: 'todo', effort: 'quick' },
    ],
  },
]
