import type { WorkArea, Effort } from '@/shared/types'

export interface WorkTemplate {
  id: string
  title: string
  description: string
  area: WorkArea
  subArea?: string
  effort: Effort
  must: boolean
  items: { id: string; label: string; optional?: boolean }[]
}

export const financeTemplates: WorkTemplate[] = [
  {
    id: 'tmpl-fin-payment-request',
    title: 'Payment Request Processing',
    description: 'End-to-end flow for handling an incoming payment request.',
    area: 'finance',
    subArea: 'Payments',
    effort: 'quick',
    must: false,
    items: [
      { id: '1', label: 'Receive and verify payment request details' },
      { id: '2', label: 'Check against budget / approval threshold' },
      { id: '3', label: 'Obtain required approvals (email / Lark)' },
      { id: '4', label: 'Process payment via banking platform' },
      { id: '5', label: 'Confirm receipt with requestor' },
      { id: '6', label: 'Archive supporting documents' },
    ],
  },
  {
    id: 'tmpl-fin-expense-reimbursement',
    title: 'Expense Reimbursement',
    description: 'Process employee expense claims from submission to payment.',
    area: 'finance',
    subArea: 'Payments',
    effort: 'medium',
    must: false,
    items: [
      { id: '1', label: 'Collect receipts and expense form from employee' },
      { id: '2', label: 'Verify amounts against policy limits' },
      { id: '3', label: 'Get manager sign-off' },
      { id: '4', label: 'Process reimbursement transfer' },
      { id: '5', label: 'Send payment confirmation to employee' },
      { id: '6', label: 'Archive to expense records' },
    ],
  },
  {
    id: 'tmpl-fin-budget-amendment',
    title: 'Budget Amendment',
    description: 'Formal process for requesting and approving a budget change.',
    area: 'finance',
    subArea: 'Budgets',
    effort: 'heavy',
    must: false,
    items: [
      { id: '1', label: 'Prepare current-state budget report' },
      { id: '2', label: 'Draft amendment with variance analysis' },
      { id: '3', label: 'Internal review and sense-check' },
      { id: '4', label: 'Submit to CFO / approving authority' },
      { id: '5', label: 'Incorporate feedback and finalize' },
      { id: '6', label: 'Update financial records and notify relevant teams' },
    ],
  },
  {
    id: 'tmpl-fin-bank-account-setup',
    title: 'New Bank Account Setup',
    description: 'Open a new corporate bank account end-to-end.',
    area: 'finance',
    subArea: 'Administrative',
    effort: 'medium',
    must: false,
    items: [
      { id: '1', label: 'Prepare KYC and corporate documents' },
      { id: '2', label: 'Submit application to bank' },
      { id: '3', label: 'Follow up with bank for status' },
      { id: '4', label: 'Complete any additional onboarding requirements' },
      { id: '5', label: 'Receive account details and set up signatories' },
      { id: '6', label: 'Update internal records and notify ops/finance team' },
    ],
  },
  {
    id: 'tmpl-fin-reconciliation',
    title: 'Bank Reconciliation',
    description: 'Ad-hoc reconciliation of bank statement against ledger.',
    area: 'finance',
    subArea: 'Records',
    effort: 'medium',
    must: false,
    items: [
      { id: '1', label: 'Download bank statement' },
      { id: '2', label: 'Match transactions against accounting records' },
      { id: '3', label: 'Investigate and resolve discrepancies' },
      { id: '4', label: 'Prepare reconciliation summary' },
      { id: '5', label: 'Get sign-off and archive' },
    ],
  },
  {
    id: 'tmpl-fin-audit-prep',
    title: 'Audit Preparation',
    description: 'Gather and organize documents for an internal or external audit.',
    area: 'finance',
    subArea: 'Records',
    effort: 'heavy',
    must: true,
    items: [
      { id: '1', label: 'Confirm audit scope and timeline with auditors' },
      { id: '2', label: 'Compile requested documents (invoices, contracts, bank statements)' },
      { id: '3', label: 'Internal pre-audit review for gaps' },
      { id: '4', label: 'Prepare management accounts and schedules' },
      { id: '5', label: 'Brief relevant staff on audit process' },
      { id: '6', label: 'Respond to auditor queries' },
      { id: '7', label: 'Sign off final audit report' },
    ],
  },
]

export const hrTemplates: WorkTemplate[] = [
  {
    id: 'tmpl-hr-onboarding',
    title: 'New Employee Onboarding',
    description: 'Full onboarding checklist from offer acceptance to first week.',
    area: 'hr',
    subArea: 'Onboarding & Offboarding',
    effort: 'heavy',
    must: true,
    items: [
      { id: '1', label: 'Prepare and send offer letter' },
      { id: '2', label: 'Collect signed offer, HKID copy, bank details' },
      { id: '3', label: 'Submit MPF enrollment' },
      { id: '4', label: 'Set up IT accounts (email, Lark, systems)' },
      { id: '5', label: 'Arrange access card and desk' },
      { id: '6', label: 'Send Day 1 briefing and welcome email' },
      { id: '7', label: '1-week check-in with new employee' },
      { id: '8', label: 'Archive to employee file' },
    ],
  },
  {
    id: 'tmpl-hr-offboarding',
    title: 'Employee Offboarding',
    description: 'Structured checklist for a smooth and compliant departure.',
    area: 'hr',
    subArea: 'Onboarding & Offboarding',
    effort: 'heavy',
    must: true,
    items: [
      { id: '1', label: 'Accept resignation in writing, confirm last day' },
      { id: '2', label: 'Schedule exit interview' },
      { id: '3', label: 'Calculate final salary and any outstanding leave' },
      { id: '4', label: 'Notify IT to decommission accounts on last day' },
      { id: '5', label: 'Collect company assets (laptop, access card)' },
      { id: '6', label: 'Issue MPF cessation and final payroll' },
      { id: '7', label: 'Prepare reference letter if requested', optional: true },
      { id: '8', label: 'Archive employee file' },
    ],
  },
  {
    id: 'tmpl-hr-visa',
    title: 'Work Permit / Visa Application',
    description: 'End-to-end visa or work permit application for a new or existing employee.',
    area: 'hr',
    subArea: 'Insurance & VISA',
    effort: 'heavy',
    must: false,
    items: [
      { id: '1', label: 'Check eligibility and visa category' },
      { id: '2', label: 'Gather required documents (passport, proof of employment, sponsor letter)' },
      { id: '3', label: 'Prepare and verify application form' },
      { id: '4', label: 'Submit to Immigration Department / Embassy' },
      { id: '5', label: 'Follow up on application status' },
      { id: '6', label: 'Collect visa / permit on approval' },
      { id: '7', label: 'Update employee records and calendar reminder for renewal' },
    ],
  },
  {
    id: 'tmpl-hr-mpf-enrollment',
    title: 'MPF Enrollment',
    description: 'Enroll a new employee into the company MPF scheme.',
    area: 'hr',
    subArea: 'Payroll & MPF',
    effort: 'medium',
    must: false,
    items: [
      { id: '1', label: 'Confirm employee eligibility (>18 yrs, employment type)' },
      { id: '2', label: 'Provide employee with scheme information and election form' },
      { id: '3', label: 'Collect signed enrollment form' },
      { id: '4', label: 'Submit to MPF trustee' },
      { id: '5', label: 'Confirm enrollment receipt from trustee' },
      { id: '6', label: 'Set up payroll deduction in system' },
    ],
  },
  {
    id: 'tmpl-hr-leave-processing',
    title: 'Annual Leave Processing',
    description: 'Handle a batch of leave requests or year-end leave reconciliation.',
    area: 'hr',
    subArea: 'Leave & Attendance',
    effort: 'quick',
    must: false,
    items: [
      { id: '1', label: 'Collect leave request forms / system submissions' },
      { id: '2', label: 'Verify against leave balance and policy' },
      { id: '3', label: 'Get manager approval' },
      { id: '4', label: 'Update leave records in system' },
      { id: '5', label: 'Confirm to employee and notify team calendar' },
    ],
  },
]

export const opsTemplates: WorkTemplate[] = [
  {
    id: 'tmpl-ops-vendor-onboarding',
    title: 'New Vendor Onboarding',
    description: 'Due diligence and setup for a new supplier or service provider.',
    area: 'ops',
    subArea: 'Vendor & Contracts',
    effort: 'heavy',
    must: false,
    items: [
      { id: '1', label: 'Conduct due diligence (company registration, references)' },
      { id: '2', label: 'Request and review commercial proposal' },
      { id: '3', label: 'Send NDA for signature' },
      { id: '4', label: 'Draft / review service agreement' },
      { id: '5', label: 'Legal review', optional: true },
      { id: '6', label: 'Execute contract (wet or e-signature)' },
      { id: '7', label: 'Set up vendor in payment system' },
      { id: '8', label: 'File contract and add renewal reminder to calendar' },
    ],
  },
  {
    id: 'tmpl-ops-contract-renewal',
    title: 'Contract Renewal',
    description: 'Review and renew an expiring supplier or office contract.',
    area: 'ops',
    subArea: 'Vendor & Contracts',
    effort: 'medium',
    must: false,
    items: [
      { id: '1', label: 'Review current contract terms and expiry date' },
      { id: '2', label: 'Assess performance / value — renew or re-tender?' },
      { id: '3', label: 'Negotiate updated terms / pricing' },
      { id: '4', label: 'Legal / internal review if terms change significantly', optional: true },
      { id: '5', label: 'Execute renewal agreement' },
      { id: '6', label: 'Update contract file and calendar reminder' },
    ],
  },
  {
    id: 'tmpl-ops-purchase-order',
    title: 'Office Purchase Order',
    description: 'End-to-end process for purchasing office equipment or supplies.',
    area: 'ops',
    subArea: 'Expenses',
    effort: 'medium',
    must: false,
    items: [
      { id: '1', label: 'Receive purchase request with specs' },
      { id: '2', label: 'Get at least 3 quotes (or justify single source)' },
      { id: '3', label: 'Obtain internal approval (budget holder / CFO)' },
      { id: '4', label: 'Raise purchase order' },
      { id: '5', label: 'Place order and track delivery' },
      { id: '6', label: 'Receive goods — verify against PO' },
      { id: '7', label: 'Approve and pay invoice' },
      { id: '8', label: 'Record asset / expense in system' },
    ],
  },
  {
    id: 'tmpl-ops-travel',
    title: 'Business Travel Arrangement',
    description: 'Coordinate flights, hotel, and logistics for a business trip.',
    area: 'ops',
    subArea: 'Arrangements',
    effort: 'medium',
    must: false,
    items: [
      { id: '1', label: 'Confirm travel dates, destination, and traveller details' },
      { id: '2', label: 'Check visa requirements', optional: true },
      { id: '3', label: 'Book flights (preferred carrier / class policy)' },
      { id: '4', label: 'Book hotel (preferred rate / proximity to meetings)' },
      { id: '5', label: 'Arrange airport transfer if needed', optional: true },
      { id: '6', label: 'Purchase travel insurance' },
      { id: '7', label: 'Send itinerary to traveller and block calendar' },
      { id: '8', label: 'Post-trip: collect receipts for expense claim' },
    ],
  },
  {
    id: 'tmpl-ops-event',
    title: 'Corporate Event Planning',
    description: 'Plan and execute an internal or client-facing event.',
    area: 'ops',
    subArea: 'Arrangements',
    effort: 'heavy',
    must: false,
    items: [
      { id: '1', label: 'Define event scope, budget, and attendee list' },
      { id: '2', label: 'Source and confirm venue' },
      { id: '3', label: 'Arrange catering' },
      { id: '4', label: 'Send invitations and manage RSVPs' },
      { id: '5', label: 'Arrange AV, décor, logistics' },
      { id: '6', label: 'Confirm run-of-show / agenda' },
      { id: '7', label: 'On-day coordination' },
      { id: '8', label: 'Post-event: thank you comms, feedback, invoice settlement' },
    ],
  },
]
