import type { Cycle } from '@/shared/types'

export const hrCycles: Cycle[] = [
  {
    id: 'ai-hr-system',
    title: 'AI HR System',
    area: 'hr',
    subArea: 'AI',
    effort: 'heavy',
    must: false,
    triggerLabel: '',
    status: 'active',
    items: [
      { id: 'ahs1', label: 'Prep dummy for Chris', status: 'todo', effort: 'medium' },
      { id: 'ahs2', label: 'Schedule meeting with Chris', status: 'todo', effort: 'quick', waitingOn: true },
      { id: 'ahs3', label: 'Tasks TBC', status: 'todo', effort: 'medium' },
    ],
  },
  {
    id: 'payroll',
    title: 'Payroll',
    area: 'hr',
    subArea: 'Payroll & MPF',
    effort: 'heavy',
    must: true,
    triggerLabel: 'Phase 1: 20th · Phase 2: Last 5 days · Phase 3: 1st work day',
    status: 'upcoming',
    phases: [
      {
        id: 'payroll-planning',
        title: 'Phase 1 — Planning',
        triggerLabel: 'Starts 20th of month',
        effort: 'heavy',
        must: true,
        status: 'upcoming',
        items: [
          { id: 'p1a', label: 'Check notes', status: 'todo', effort: 'quick' },
          { id: 'p1b', label: 'Generate new month payroll', status: 'todo', effort: 'medium' },
          { id: 'p1c', label: 'Ask for MOD salaries + check with CFO', status: 'todo', effort: 'quick', waitingOn: true },
          { id: 'p1d', label: 'Confirm budget', status: 'todo', effort: 'quick' },
          { id: 'p1e', label: 'Ask team leaders to fill in HR headcount cost sheets', status: 'todo', effort: 'quick', waitingOn: true },
        ],
      },
      {
        id: 'payroll-settlement',
        title: 'Phase 2 — Settlement',
        triggerLabel: 'Last 5 days of month',
        effort: 'heavy',
        must: true,
        status: 'upcoming',
        items: [
          { id: 'p2a', label: 'Send email to BCOM', status: 'todo', effort: 'quick' },
          { id: 'p2b', label: 'Fiat: EV Tech BCOM, Apexco BCOM, DT HSBC, OA Airwallex, ADFL Zand', status: 'todo', effort: 'heavy' },
          { id: 'p2c', label: 'Fiat: GAHK Shacom', status: 'todo', effort: 'medium' },
          { id: 'p2d', label: 'Crypto: plan crypto settlement', status: 'todo', effort: 'medium' },
          { id: 'p2e', label: 'Arrange funds from sub-account to main account + records', status: 'todo', effort: 'medium' },
          { id: 'p2f', label: 'Crypto + MOD salaries settlement', status: 'todo', effort: 'medium' },
        ],
      },
      {
        id: 'payroll-2nd-round',
        title: 'Phase 3 — 2nd Round Settlement',
        triggerLabel: '1st work day of next month',
        effort: 'heavy',
        must: true,
        status: 'upcoming',
        items: [
          { id: 'p3a', label: 'Settle driver salary + PT salary', status: 'todo', effort: 'medium' },
          { id: 'p4', label: 'HR headcount cost', status: 'todo', effort: 'quick' },
        ],
      },
    ],
  },
  {
    id: 'mpf',
    title: 'MPF Filing',
    area: 'hr',
    subArea: 'Payroll & MPF',
    effort: 'heavy',
    must: true,
    urgent: true,
    triggerLabel: 'Last 5 days of month',
    status: 'upcoming',
    items: [
      {
        id: 'mpf1',
        label: 'eMPF portal — submit for all entities',
        status: 'todo',
        effort: 'heavy',
        subItems: [
          { id: 'mpf1a', label: 'Apexco', status: 'todo', effort: 'quick' },
          { id: 'mpf1b', label: 'EVGM', status: 'todo', effort: 'quick' },
          { id: 'mpf1c', label: 'DT', status: 'todo', effort: 'quick' },
          { id: 'mpf1d', label: 'GAHK', status: 'todo', effort: 'quick' },
          { id: 'mpf1e', label: 'Duom', status: 'todo', effort: 'quick' },
          { id: 'mpf1f', label: 'EV Tech', status: 'todo', effort: 'quick' },
        ],
      },
      {
        id: 'mpf2',
        label: 'Prepare settlement per entity',
        status: 'todo',
        effort: 'medium',
        subItems: [
          { id: 'mpf2a', label: 'Apexco — savings account', status: 'todo', effort: 'quick' },
          { id: 'mpf2b', label: 'EVGM — savings account', status: 'todo', effort: 'quick' },
          { id: 'mpf2c', label: 'DT — cheque', status: 'todo', effort: 'quick' },
          { id: 'mpf2d', label: 'GAHK — savings account', status: 'todo', effort: 'quick' },
          { id: 'mpf2e', label: 'Duom — checking account', status: 'todo', effort: 'quick' },
          { id: 'mpf2f', label: 'EV Tech — savings account', status: 'todo', effort: 'quick' },
        ],
      },
      {
        id: 'mpf3',
        label: 'Check new joiner applications',
        status: 'todo',
        effort: 'quick',
        optional: true,
        subItems: [
          { id: 'mpf3a', label: '(Skip if no new joiners this month)', status: 'todo', effort: 'quick', optional: true },
        ],
      },
    ],
  },
  {
    id: 'hr-overhead-cost',
    title: 'HR Overhead Cost',
    area: 'hr',
    subArea: 'Records',
    effort: 'quick',
    must: true,
    triggerLabel: 'Last 5 days of month',
    status: 'upcoming',
    items: [
      { id: 'hroc1', label: 'Update internal Google Sheet', status: 'todo', effort: 'quick', url: 'internal-sheet' },
      { id: 'hroc2', label: 'Update accounting Google Sheet', status: 'todo', effort: 'quick', url: 'internal-sheet' },
    ],
  },
]
